In [1]:
# import libraries
import pandas as pd
import glob 
import os

In [2]:
# reading and combining files of a folder 
pathcrime = r"C:\Users\sophi\Documents\Rockborne\Python\project2\crimes"
pathoutcome = r"C:\Users\sophi\Documents\Rockborne\Python\project2\outcomes"

crime_files = glob.glob(os.path.join(pathcrime,"**", "*.csv"), recursive=True)
outcome_files = glob.glob(os.path.join(pathoutcome, "**", "*.csv"), recursive=True)

crimedf = pd.concat([pd.read_csv(f) for f in crime_files], ignore_index=True)
outcomedf = pd.concat([pd.read_csv(f) for f in outcome_files], ignore_index=True)
populationdf = pd.read_csv("poplulation.csv")

In [3]:
# checking columns
crimedf.columns
outcomedf.columns
populationdf.columns

Index(['LSOA 2021 Code', 'Total', 'Unnamed: 2'], dtype='object')

In [4]:
# dropped an error in columns
populationdf = populationdf.drop(columns=["Unnamed: 2"])

In [5]:
# checking if columns are correct now
crimedf.columns
outcomedf.columns
populationdf.columns

Index(['LSOA 2021 Code', 'Total'], dtype='object')

In [6]:
crimedf.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,48c1007edc34d286b599720b7518058e9f75e6928ca2dc...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",Other theft,Unable to prosecute suspect,NaN
1,4d913f4f5875e7b7726bb10f1633fdc5d3a47edd16ea5d...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,Vehicle crime,Investigation complete; no suspect identified,NaN
2,9ac9fcc7d22103973f626a69ae4c9fefd54151d5addc1e...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,Theft from the person,Action to be taken by another organisation,NaN
3,e3a99af51ec4babcb0680c0f027b7254d80ba8f168adbd...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences,Status update unavailable,NaN
4,abe881ef6ba45b35a8e1ba5b4d5de25b9140413743c286...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences,Status update unavailable,NaN

In [7]:
# check that all 4 datasets have been combined, should be 4 output with names of areas
crimedf["Reported by"].unique()

array(['Devon & Cornwall Police', 'Metropolitan Police Service',
       'North Yorkshire Police', 'West Midlands Police'], dtype=object)

In [8]:
outcomedf.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,8b0ee0ff59e93fda566a2fb85e1a826c2a3c088d953dc9...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.057772,51.079953,On or near Nightclub,E01020094,North Devon 008A,Unable to prosecute suspect
1,3fa034d50ead13b57d47ced7e613f2c45c8c7e0fba49bd...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.732752,50.463149,On or near Whitestone Road,E01018930,Cornwall 015D,Unable to prosecute suspect
2,ce96e70f67f6d9e52c1574a7d953694ad9a24fbb140472...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.133948,50.380220,On or near Chester Place,E01015050,Plymouth 023D,Unable to prosecute suspect
3,d1bd0989659b81831cd49f9fb425d105c90e2bfa3ebc26...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.183296,50.402671,On or near Tamerton Avenue,E01015144,Plymouth 009D,Unable to prosecute suspect
4,8cd3955f6d38e7e8a576a51dd3f970d1d6e81a5096857c...,2024-01,Devon & Cornwall Police,Devon & Cornwall Police,-4.796947,50.339720,On or near B3274,E01019034,Cornwall 038B,Investigation complete; no suspect identified

In [9]:
# finding nulls
crimedf.isnull().sum()

Crime ID                  616904
Month                          0
Reported by                    0
Falls within                   0
Longitude                  17169
Latitude                   17169
Location                       0
LSOA code                  17177
LSOA name                  17177
Crime type                     0
Last outcome category     616904
Context                  3493686
dtype: int64

In [10]:
# dealing the null values and dropping unnecessary columns

# crimedf["Crime ID"] = crimedf["Crime ID"].fillna("Unknown")

''' Crime ID was left unchanged as it functions as a unique identifier and is required 
to link the street crime data to the outcomes dataset. Missing values were preserved to 
avoid introducing later errors. '''


# crimedf["Longitude"] = crimedf["Longitude"].fillna("Unknown")
# crimedf["Latitude"] = crimedf["Latitude"].fillna("Unknown")
''' Longitude and Latitude was left unchanged as missing values in the columns were 
retained as NaN to avoid introducing inaccurate geographic coordinates. Changing these to 
'Unknown' would also change the column to the incorrect datatype, by leaving NaN, the
datatype stays correctly as float rather than object. '''

crimedf["LSOA code"] = crimedf["LSOA code"].fillna("Unknown")
crimedf["LSOA name"] = crimedf["LSOA name"].fillna("Unknown")


crimedf = crimedf.drop(columns=["Context" , "Last outcome category"])

''' The column "Last outcome category" contained a large number of missing values 
and was removed from the dataset. Since a separate outcomes dataset was obtained 
from the UK Police Data platform, this column was considered redundant for the analysis.'''

' The column "Last outcome category" contained a large number of missing values \nand was removed from the dataset. Since a separate outcomes dataset was obtained \nfrom the UK Police Data platform, this column was considered redundant for the analysis.'

In [11]:
# check there are no more nulls, Crime ID should be the only column with null.

crimedf.isnull().sum()

# crimedf.head() # to see if there are still values in the dataframe.

Crime ID        616904
Month                0
Reported by          0
Falls within         0
Longitude        17169
Latitude         17169
Location             0
LSOA code            0
LSOA name            0
Crime type           0
dtype: int64

In [12]:
# check if nulls in outcome dataframe
outcomedf.isnull().sum()

Crime ID            0
Month               0
Reported by         0
Falls within        0
Longitude       19442
Latitude        19442
Location            0
LSOA code       19448
LSOA name       19448
Outcome type        0
dtype: int64

In [13]:
# replacing nulls with Unknown
outcomedf["LSOA code"] = outcomedf["LSOA code"].fillna("Unknown")
outcomedf["LSOA name"] = outcomedf["LSOA name"].fillna("Unknown")

In [14]:
# checking if nulls replaced was successful
outcomedf.isnull().sum()

Crime ID            0
Month               0
Reported by         0
Falls within        0
Longitude       19442
Latitude        19442
Location            0
LSOA code           0
LSOA name           0
Outcome type        0
dtype: int64

In [15]:
# checking for duplicate records

crimedf.duplicated().sum()

np.int64(265153)

In [16]:
# drop duplicates if all columns in a row is duplicated

crimedf = crimedf.drop_duplicates()

In [17]:
# checking after running drop_duplicates(), should be 0 duplicates

crimedf.duplicated().sum()

np.int64(0)

In [18]:
# duplicates for outcome
outcomedf.duplicated().sum()

np.int64(283263)

In [19]:
# drop the duplicates
outcomedf = outcomedf.drop_duplicates()

In [20]:
# check if successful
outcomedf.duplicated().sum()

np.int64(0)

In [21]:
# verifying the data types

crimedf.dtypes

Crime ID         object
Month            object
Reported by      object
Falls within     object
Longitude       float64
Latitude        float64
Location         object
LSOA code        object
LSOA name        object
Crime type       object
dtype: object

In [22]:
# changing Month to datetime to be able to analyse crimed trends over time

crimedf["Month"] = pd.to_datetime(crimedf["Month"])

In [23]:
# verify change took place 

crimedf.dtypes

# crimedf["Month"].head() # check the format

Crime ID                object
Month           datetime64[ns]
Reported by             object
Falls within            object
Longitude              float64
Latitude               float64
Location                object
LSOA code               object
LSOA name               object
Crime type              object
dtype: object

In [24]:
outcomedf.dtypes

Crime ID         object
Month            object
Reported by      object
Falls within     object
Longitude       float64
Latitude        float64
Location         object
LSOA code        object
LSOA name        object
Outcome type     object
dtype: object

In [25]:
# convert month column into separate year and month dates, to allow for yearly and monthly analysis

month_index = crimedf.columns.get_loc("Month")
crimedf.insert(month_index, "Year", crimedf["Month"].dt.year)

crimedf["Month"] = crimedf["Month"].dt.month_name()

crimedf.head()

,Crime ID,Year,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type
0,48c1007edc34d286b599720b7518058e9f75e6928ca2dc...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",Other theft
1,4d913f4f5875e7b7726bb10f1633fdc5d3a47edd16ea5d...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,Vehicle crime
2,9ac9fcc7d22103973f626a69ae4c9fefd54151d5addc1e...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,Theft from the person
3,e3a99af51ec4babcb0680c0f027b7254d80ba8f168adbd...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences
4,abe881ef6ba45b35a8e1ba5b4d5de25b9140413743c286...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences

In [26]:
outcomedf["Month"] = pd.to_datetime(outcomedf["Month"])

In [27]:
month_index = outcomedf.columns.get_loc("Month")
outcomedf.insert(month_index, "Year", outcomedf["Month"].dt.year)

outcomedf["Month"] = outcomedf["Month"].dt.month_name()

outcomedf.head()

,Crime ID,Year,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,8b0ee0ff59e93fda566a2fb85e1a826c2a3c088d953dc9...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.057772,51.079953,On or near Nightclub,E01020094,North Devon 008A,Unable to prosecute suspect
1,3fa034d50ead13b57d47ced7e613f2c45c8c7e0fba49bd...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.732752,50.463149,On or near Whitestone Road,E01018930,Cornwall 015D,Unable to prosecute suspect
2,ce96e70f67f6d9e52c1574a7d953694ad9a24fbb140472...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.133948,50.380220,On or near Chester Place,E01015050,Plymouth 023D,Unable to prosecute suspect
3,d1bd0989659b81831cd49f9fb425d105c90e2bfa3ebc26...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.183296,50.402671,On or near Tamerton Avenue,E01015144,Plymouth 009D,Unable to prosecute suspect
4,8cd3955f6d38e7e8a576a51dd3f970d1d6e81a5096857c...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.796947,50.339720,On or near B3274,E01019034,Cornwall 038B,Investigation complete; no suspect identified

In [28]:
# checking the coordinates are within range for crimedf
# uk coordinates usually fall between
# longtitude = -8 - 2
# latitude = 49 - 61
crimedf[["Longitude","Latitude"]].describe()

          Longitude      Latitude
count  3.211785e+06  3.211785e+06
mean  -8.836858e-01  5.172529e+01
std    1.263782e+00  7.050867e-01
min   -7.340312e+00  4.989213e+01
25%   -1.825501e+00  5.147145e+01
50%   -1.986320e-01  5.153103e+01
75%   -7.958100e-02  5.167044e+01
max    1.745418e+00  5.579090e+01

In [29]:
# checking the coordinates are within range for outcomedf
# uk coordinates usually fall between
# longtitude = -8 - 2
# latitude = 49 - 61
outcomedf[["Longitude","Latitude"]].describe()

          Longitude      Latitude
count  2.878483e+06  2.878483e+06
mean  -9.283658e-01  5.173379e+01
std    1.279773e+00  7.027832e-01
min   -7.340312e+00  4.989213e+01
25%   -1.859084e+00  5.147275e+01
50%   -2.069180e-01  5.153341e+01
75%   -8.373700e-02  5.240518e+01
max    1.745418e+00  5.579090e+01

In [30]:
# separate the LSOA name into districts as an extra column for crimedf

crimedf["District"] = crimedf["LSOA name"].str.extract(r"^(.*?)(?=\s\d)")

In [31]:
# check if successful
crimedf[["LSOA name","District"]].head()

,LSOA name,District
0,"Bournemouth, Christchurch and Poole 016E","Bournemouth, Christchurch and Poole"
1,Bracknell Forest 010D,Bracknell Forest
2,Bristol 061C,Bristol
3,Cannock Chase 003B,Cannock Chase
4,Cannock Chase 003B,Cannock Chase

In [32]:
crimedf["District"] = crimedf["District"].fillna("Unknown")

In [33]:
# separate the LSOA name into districts as an extra column for outcomedf

outcomedf["District"] = outcomedf["LSOA name"].str.extract(r"^(.*?)(?=\s\d)")

In [34]:
# check if successful
outcomedf[["LSOA name","District"]].head()

          LSOA name     District
0  North Devon 008A  North Devon
1     Cornwall 015D     Cornwall
2     Plymouth 023D     Plymouth
3     Plymouth 009D     Plymouth
4     Cornwall 038B     Cornwall

In [ ]:
# replacing nulls
outcomedf["District"] = outcomedf["District"].fillna("Unknown")

In [ ]:
# checking all columns are right
crimedf.columns

Index(['Crime ID', 'Year', 'Month', 'Reported by', 'Falls within', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Crime type',
       'District'],
      dtype='object')

In [37]:
outcomedf.columns

Index(['Crime ID', 'Year', 'Month', 'Reported by', 'Falls within', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Outcome type',
       'District'],
      dtype='object')

In [ ]:
# first merging crimedf with outcomedf to isolate problems if any
merged_df = pd.merge(
    crimedf,
    outcomedf,
    on="Crime ID",
    how="left",
    suffixes=("_crime", "_outcome")
)

In [39]:
merged_df.head()
# merged_df.shape
# merged_df.columns

,Crime ID,Year_crime,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,...,Month_outcome,Reported by_outcome,Falls within_outcome,Longitude_outcome,Latitude_outcome,Location_outcome,LSOA code_outcome,LSOA name_outcome,Outcome type,District_outcome
0,48c1007edc34d286b599720b7518058e9f75e6928ca2dc...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",...,March,Devon & Cornwall Police,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",Unable to prosecute suspect,"Bournemouth, Christchurch and Poole"
1,4d913f4f5875e7b7726bb10f1633fdc5d3a47edd16ea5d...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,...,January,Devon & Cornwall Police,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,Investigation complete; no suspect identified,Bracknell Forest
2,9ac9fcc7d22103973f626a69ae4c9fefd54151d5addc1e...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,...,January,Devon & Cornwall Police,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,Action to be taken by another organisation,Bristol
3,e3a99af51ec4babcb0680c0f027b7254d80ba8f168adbd...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,abe881ef6ba45b35a8e1ba5b4d5de25b9140413743c286...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
populationdf.head()

  LSOA 2021 Code  Total
0      E01011949  1,898
1      E01011950  1,247
2      E01011951  1,393
3      E01011952  1,669
4      E01011953  2,303

In [ ]:
# removing duplicate columns
merged_df = merged_df.drop(columns=[
    "Longitude_outcome",
    "Latitude_outcome",
    "Year_outcome",
    "Month_outcome",
    "LSOA code_outcome",
    "LSOA name_outcome",
    "Location_outcome",
    "Reported by_outcome",
    "Falls within_outcome",
    "District_outcome"
])

In [55]:
merged_df.head()

,Crime ID,Year_crime,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,Crime type,District_crime,Outcome type
0,48c1007edc34d286b599720b7518058e9f75e6928ca2dc...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",Other theft,"Bournemouth, Christchurch and Poole",Unable to prosecute suspect
1,4d913f4f5875e7b7726bb10f1633fdc5d3a47edd16ea5d...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,Vehicle crime,Bracknell Forest,Investigation complete; no suspect identified
2,9ac9fcc7d22103973f626a69ae4c9fefd54151d5addc1e...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,Theft from the person,Bristol,Action to be taken by another organisation
3,e3a99af51ec4babcb0680c0f027b7254d80ba8f168adbd...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences,Cannock Chase,Unknown
4,abe881ef6ba45b35a8e1ba5b4d5de25b9140413743c286...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences,Cannock Chase,Unknown

In [56]:
merged_df.isnull().sum()

Crime ID              362192
Year_crime                 0
Month_crime                0
Reported by_crime          0
Falls within_crime         0
Longitude_crime        17143
Latitude_crime         17143
Location_crime             0
LSOA code_crime            0
LSOA name_crime            0
Crime type                 0
District_crime             0
Outcome type               0
dtype: int64

In [45]:
# merged_df["District_crime"] = merged_df["District_crime"].fillna("Unknown")
merged_df["Outcome type"] = merged_df["Outcome type"].fillna("Unknown")

In [ ]:
# merging sub df with populationdf to make main df
df = pd.merge(
    merged_df,
    populationdf,
    left_on="LSOA code_crime",
    right_on="LSOA 2021 Code",
    how="inner"   # keeps records that only matches
)

In [ ]:
df.head(20)

,Crime ID,Year_crime,Month_crime,Reported by_crime,Falls within_crime,Longitude_crime,Latitude_crime,Location_crime,LSOA code_crime,LSOA name_crime,...,Falls within_outcome,Longitude_outcome,Latitude_outcome,Location_outcome,LSOA code_outcome,LSOA name_outcome,Outcome type,District_outcome,LSOA 2021 Code,Total
0,48c1007edc34d286b599720b7518058e9f75e6928ca2dc...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",...,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",Unable to prosecute suspect,"Bournemouth, Christchurch and Poole",E01015411,"1,319"
1,4d913f4f5875e7b7726bb10f1633fdc5d3a47edd16ea5d...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,...,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,Investigation complete; no suspect identified,Bracknell Forest,E01016231,"1,975"
2,9ac9fcc7d22103973f626a69ae4c9fefd54151d5addc1e...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,...,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,Action to be taken by another organisation,Bristol,E01033909,"2,321"
3,e3a99af51ec4babcb0680c0f027b7254d80ba8f168adbd...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E01029346,"1,791"
4,abe881ef6ba45b35a8e1ba5b4d5de25b9140413743c286...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E01029346,"1,791"
5,cfdf75b16ac047936da0378b2b3c7751013315a792d2b7...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-1.315645,51.832827,On or near Airport/Airfield,E01028488,Cherwell 019A,...,Devon & Cornwall Police,-1.315645,51.832827,On or near Airport/Airfield,E01028488,Cherwell 019A,Unable to prosecute suspect,Cherwell,E01028488,"1,433"
6,5e561cb7d5ad2434be4d0b8d450578de00937fa19e183a...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.544010,50.830719,On or near Queen Street,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.544010,50.830719,On or near Queen Street,E01018936,Cornwall 001A,Investigation complete; no suspect identified,Cornwall,E01018936,"1,555"
7,5e561cb7d5ad2434be4d0b8d450578de00937fa19e183a...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.544010,50.830719,On or near Queen Street,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.544010,50.830719,On or near Queen Street,E01018936,Cornwall 001A,Unable to prosecute suspect,Cornwall,E01018936,"1,555"
8,2d58ba0a4ab6f7327010952f77157aa178e1b0c1cf143a...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.546005,50.831359,On or near Parking Area,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.546005,50.831359,On or near Parking Area,E01018936,Cornwall 001A,Investigation complete; no suspect identified,Cornwall,E01018936,"1,555"
9,7f3e3b5c5cf397b115fbe5287523a9af625775dc7391e2...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.544801,50.831421,On or near Princes Street,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.544801,50.831421,On or near Princes Street,E01018936,Cornwall 001A,Local resolution,Cornwall,E01018936,"1,555"
10,7f3e3b5c5cf397b115fbe5287523a9af625775dc7391e2...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.544801,50.831421,On or near Princes Street,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.544801,50.831421,On or near Princes Street,E01018936,Cornwall 001A,Investigation complete; no suspect identified,Cornwall,E01018936,"1,555"
11,d78f56e463b380638a68230fa9a29095182ec6569ebc13...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.542005,50.830184,On or near Supermarket,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.542005,50.830184,On or near Supermarket,E01018936,Cornwall 001A,Unable to prosecute suspect,Cornwall,E01018936,"1,555"
12,bb55f4f2a92ef8db7e597e1427ad5b84cbbbc4b7dca326...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.542005,50.830184,On or near Supermarket,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.542005,50.830184,On or near Supermarket,E01018936,Cornwall 001A,Investigation complete; no suspect identified,Cornwall,E01018936,"1,555"
13,bb55f4f2a92ef8db7e597e1427ad5b84cbbbc4b7dca326...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.542005,50.830184,On or near Supermarket,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.542005,50.830184,On or near Supermarket,E01018936,Cornwall 001A,Suspect charged,Cornwall,E01018936,"1,555"
14,256bd2c998cd0bd34a37f0a271969190c372b5a85f4023...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.548591,50.830340,On or near Parking Area,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.548591,50.830340,On or near Parking Area,E01018936,Cornwall 001A,Unable to prosecute suspect,Cornwall,E01018936,"1,555"
15,3d4c9ce746d8194d90e4070a8706657014fc09da72a940...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,Unable to prosecute suspect,Cornwall,E01018936,"1,555"
16,1d445b7c3b8ef4bfe269e7dd7a37699616a4579cb9c79c...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,Suspect charged,Cornwall,E01018936,"1,555"
17,8d2e2f7b17276ab78c0e109433e28e9a605801d93d8193...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,Unable to prosecute suspect,Cornwall,E01018936,"1,555"
18,917790d1501720d4f13134cc72607b8d0015b5c0a44658...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.543922,50.827267,On or near Nightclub,E01018936,Cornwall 001A,Investigation complete; no suspect identified,Cornwall,E01018936,"1,555"
19,615d7f2f1748d78c2495d44ef51604082c9140a0d2f3aa...,2024,January,Devon & Cornwall Police,Devon & Cornwall Police,-4.546005,50.831359,On or near Parking Area,E01018936,Cornwall 001A,...,Devon & Cornwall Police,-4.546005,50.831359,On or near Parking Area,E01018936,Cornwall 001A,Unable to prosecute suspect,Cornwall,E01018936,"1,555"

In [ ]:
# changing the names of column titles

df = df.rename(columns={
    "Year_crime": "Year",
    "Month_crime": "Month",
    "Reported by_crime" : "Reported by",
    "Longitude_crime": "Longitude",
    "Latitude_crime": "Latitude",
    "Location_crime": "Location",
    "LSOA code_crime": "LSOA code",
    "LSOA name_crime": "LSOA name",
    "District_crime": "District",
    "Total" : "Population"
})

In [77]:
df.head()

,Crime ID,Year,Month,Reported by,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,District,Outcome type,Population
0,48c1007edc34d286b599720b7518058e9f75e6928ca2dc...,2024,January,Devon & Cornwall Police,-1.961000,50.745104,On or near Calder Road,E01015411,"Bournemouth, Christchurch and Poole 016E",Other theft,"Bournemouth, Christchurch and Poole",Unable to prosecute suspect,1319
1,4d913f4f5875e7b7726bb10f1633fdc5d3a47edd16ea5d...,2024,January,Devon & Cornwall Police,-0.758195,51.397477,On or near Fitzroy Close,E01016231,Bracknell Forest 010D,Vehicle crime,Bracknell Forest,Investigation complete; no suspect identified,1975
2,9ac9fcc7d22103973f626a69ae4c9fefd54151d5addc1e...,2024,January,Devon & Cornwall Police,-2.599344,51.450094,On or near Nightclub,E01033909,Bristol 061C,Theft from the person,Bristol,Action to be taken by another organisation,2321
3,e3a99af51ec4babcb0680c0f027b7254d80ba8f168adbd...,2024,January,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences,Cannock Chase,Unknown,1791
4,abe881ef6ba45b35a8e1ba5b4d5de25b9140413743c286...,2024,January,Devon & Cornwall Police,-1.933391,52.751848,On or near Hilltop,E01029346,Cannock Chase 003B,Violence and sexual offences,Cannock Chase,Unknown,1791

In [70]:
# checking types
df.dtypes

Crime ID         object
Year              int32
Month            object
Reported by      object
Longitude       float64
Latitude by     float64
Location         object
LSOA code        object
LSOA name        object
Crime type       object
District         object
Outcome type     object
Population        int64
dtype: object

In [71]:
df["Population"] = df["Population"].str.replace(",", "").astype(int)

AttributeError: Can only use .str accessor with string values!

In [72]:
df.dtypes

Crime ID         object
Year              int32
Month            object
Reported by      object
Longitude       float64
Latitude by     float64
Location         object
LSOA code        object
LSOA name        object
Crime type       object
District         object
Outcome type     object
Population        int64
dtype: object

In [ ]:
df = df.drop(columns=["LSOA 2021 Code"])
df = df.drop(columns=["Falls within_crime"])

In [78]:
# exporting as csv to be used for EDA stage
df.to_csv("cleaned_crime_data.csv", index=False)